services:
  nginx:
    image: ${DOCKERHUB_USERNAME}/django-nginx
    build:
      context: ./nginx
    ports:
    - "8081:80"
    restart: always
    depends_on:
    - django_app
    networks:
    - three_tier

  django_app:
    image: ${DOCKERHUB_USERNAME}/docker-django-notes-app-django_app
    build:
      context: .
    networks:
    - three_tier
    container_name: "django_cont"
    ports:
    - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
    - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
    - three_tier
networks:
  three_tier:



